# Generated by Django 4.2.3 on 2023-07-16 15:31

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_role'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.models.UserCManager()),
            ],
        ),
    ]
