# Generated by Django 4.2.3 on 2023-07-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_lesson_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='url_video',
            field=models.URLField(blank=True, null=True, verbose_name='ссылка на видео'),
        ),
    ]
