# Generated by Django 4.2.3 on 2023-08-01 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.BooleanField(default=False, verbose_name='статус подписки'),
        ),
    ]
