# Generated by Django 4.2.4 on 2023-08-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_alter_subscription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.PositiveIntegerField(default=10000, verbose_name='стоимость курса'),
        ),
    ]
